name: lustra
description: "Media reimagined"
publish_to: 'none'
version: 1.0.2+23

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: ^1.0.8
  crypto: ^3.0.3
  flutter_facebook_auth: ^7.1.1
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  http: ^1.1.0
  shared_preferences: ^2.2.0
  provider: ^6.0.5
  flutter_markdown: ^0.7.7
  cached_network_image: ^3.2.3
  flutter_svg: ^2.1.0
  transparent_image: ^2.0.1
  cloud_functions: ^5.5.0
  intl: 0.19.0
  url_launcher: ^6.0.0
  google_sign_in: ^6.2.1
  widgets_to_image: ^2.0.1
  share_plus: ^7.2.2
  go_router: ^16.0.0
  in_app_purchase: ^3.2.3
  firebase_app_check: ^0.3.2+10
  package_info_plus: ^8.3.1
  firebase_remote_config: ^5.5.0
  flutter_email_sender: ^7.0.0
  sign_in_with_apple: ^6.1.1
  firebase_messaging: ^15.2.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/flags/
    - assets/google_logo.svg
    - assets/ja.jpg
    - assets/logo_full.svg
  
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo_high_res_main.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/logo_high_res_foreground.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/logo_full_splash.png
  android: true
  ios: true
  android_12:
    color: "#FFFFFF"
    image: assets/logo_full_splash.png
